name: Overview
on:
  schedule: [{ cron: "0 * * * *" }]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.overview.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: mrx7014
          template: classic
          base: header, activity, community
          config_timezone: Asia/Calcutta
