name: Recent Activity
on:
  schedule: [{ cron: "0 * * * *" }]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: mrx7014
          template: classic
          base: ""
          config_timezone: Asia/Calcutta
          plugin_activity: yes
          plugin_activity_days: 31
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
          plugin_activity_limit: 4
          plugin_activity_load: 300
          plugin_activity_visibility: all
