name: WakaTime
on:
  schedule: [{ cron: "1 * * * *" }]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          filename: assets/metrics.plugin.wakatime.svg
          user: Envoy-VC
          template: classic
          base: ""
          config_timezone: Asia/Calcutta
          plugin_wakatime: yes
          plugin_wakatime_days: 365
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: current
